### ISSUE TITLE
Idea: Move from classes to data-* attributes?

### ISSUE THREAD

**Issue by tomasvn** [oliverisMisiunas/jslim-library#12]
- It might be a bit confusing when reading those classes in html
- A better approach might be move those js classes into data-* attributes?
- Example: `<h1 data-slim="add-on-click">...</h1>` vs `<h1 data-slim="aoc">...</h1>` vs `<h1 class="jadd">...</h1>`
- `aoc` - would be `add-on-click`
- Opened to suggestions @oliverisMisiunas

**Comment by oliverisMisiunas** [comment]
Thank you for your suggestion. This would require quite a significant change for the whole project. Some code would have to be rewritten, also, the tutorials for creating and using the JSlim classes would have to be changed too. I'm afraid I will have to turn down your suggestion. However, I really appreciate you making these suggestions.
