### ISSUE TITLE
CreateVariable not working as expected

### ISSUE THREAD

**Issue by timmy-83** [oliverisMisiunas/jslim-library#13]
Getting a 'textElement undefined' error following the documentation on this one. 

my HTML is 

`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>JSlim</title>
</head>
<body>

    <p class="jget textElement">text</p>

    <script type="module" src="/node_modules/jslim-library/src/index.js"></script>
    <script src="index.js"></script>
</body>
</html>`

Think my script is running before the variable is created.

I can fix by making index.js like this:

`window.addEventListener('load', ()=>{
console.log(textElement);

textElement.style.color = 'red';
})`

**Comment by timmy-83** [comment]
Also fixed with <script src="index.js" defer></script>

**Comment by oliverisMisiunas** [comment]
Thank you for pointing out this issue! I really appreciate it! I will add your name to the contributor's list. As for the issue itself, I will take a look at it later this week. Thank you very much!
